    batch_size: 64
    test_batch_size: 1000 
    epochs: 10
    lr: 1.0
    gamma: 0.7
    no_cuda: False
    dry_run: False
    seed: 1234
    log_interval: 100
    save_model: True
    file_name: "mnist_cnn.pt"